### ISSUE TITLE
Successive Filename is not working in vtree (vtree.PNG still persists rather than vtree001.PNG) 

### ISSUE THREAD

**Issue by Anandhu107** [nbarrowman/vtree#22]
When I am trying to save my file in PNG to a designated folder the file is saved as vtree.PNG. Thus for successive files, the PNG file is replaced by the new one. I read that with the new update there would be successive naming such as vtree001.PNG but it's not working yet. Could you help me with this?

**Comment by Anandhu107** [comment]
vtree(a12, c("LEVEL1","LEVEL2","LEVEL3","LEVEL4","LEVEL5"),pruneNA = TRUE, folder "xyz",format = "png",imageFileOnly = TRUE,pngknit = TRUE)

**Comment by nbarrowman** [comment]
Thanks, I'll look into this.

**Comment by Anandhu107** [comment]
Thanks a lot..!!!! it's working now.
