### ISSUE TITLE
How do you use thousand separator in vtree?

### ISSUE THREAD

**Issue by bariscr** [nbarrowman/vtree#23]
I couldn't find a way to use thousand separator for big numbers. How would that be possible?

**Comment by nbarrowman** [comment]
Good idea. I’ll take a look and see if that can be added.

**Comment by nbarrowman** [comment]
In the latest development version, I have added a parameter `thousands` to specify an optional thousands separator for big numbers. To install this version, use:
```
remotes::install_github("nbarrowman/vtree@v5.4.3",build_vignettes=TRUE)
```
Please let me know if this resolves the issue, and if you identify any problems.

**Comment by bariscr** [comment]
It works very well in the main plot. But it doesn't work in the legend. Thank you very much.

**Comment by nbarrowman** [comment]
I have now fixed the legend. Please try it:
```
remotes::install_github("nbarrowman/vtree@v5.4.3corrected",build_vignettes=TRUE)
```

**Comment by bariscr** [comment]
The legend is also fine now. Thank you so much.
