### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by TarJae** [nbarrowman/vtree#32]
Thank you for this package. 
`prunesmaller` is a very handy feature! 
`vtree(FakeData,"Severity Sex Age Category",sameline=TRUE,prunesmaller=3)`.

Is there an opposite available like `prunehigher`? 
To prune nodes that contain high numbers of observations.

**Comment by nbarrowman** [comment]
Good to hear that you're finding `prunesmaller` useful!

I have added a new parameter (I called it `prunebigger`). You can install the development version 5.6.2 from github. Instructions are in the README for this repository. Let me know if this does what you were looking for.

**Comment by TarJae** [comment]
Thank you very much. Works like charm!
