### ISSUE TITLE
Pruning using number of rows in the leaf nodes

### ISSUE THREAD

**Issue by kishorerathi** [nbarrowman/vtree#4]
Hello

Consider the following vtree code

`vtree(FakeData, "Sex Severity")`

Prints the whole tree with 4 Severity leaf nodes per Sex node. I want to prune every severity leaf node where rowcount is between 3 to 5. The resultant tree should have (Mild Moderate Severe) for Sex value of "F" and Sex value of M will have only one node of (Mild)

How can I achieve this?

Thanks for your help.

regards

K

**Comment by nbarrowman** [comment]
Pruning based on the count in a node is not currently supported in `vtree`.

**Comment by kishorerathi** [comment]
Darn!!!

Do you think this functionality has any value? And how difficult will it be to implement?

**Comment by nbarrowman** [comment]
It's not something I had thought of. Perhaps you could explain what you think the general value of such functionality would be.

**Comment by kishorerathi** [comment]
I am trying to use vtree in a Deep Learning project result presentation where we are trying to predict classes for a given image. For a test dataset I have the data in the following format

observationId, ActualClass, PredictedClass, confLevel

I have a number of observations with accepted confLevel value but with wrong predicted class.  Since it is a multiclass problem, I have a number of cases where only one or two instances of misPredictions have happened. I want to display nodes where misPredictions have happened for a given class more than a given threshold.

With the current implementation, vtree output is cluttered because of a large number of misPredictions with 1 or 2 instances. For meaningful analysis and exploration removal of these low cardinality nodes becomes important. There can be 2 variations for this functionality. 

pruneLeafNodeCondition  => it will prune the node only
pruneNonleafNodeCondition => it will prune the intermediate node and branches below it

Hope this makes sense.

**Comment by nbarrowman** [comment]
So, if I understand correctly, you are mostly interested in nodes with a minimum count. I think I can see the value of that in general. After all (as I have noted in the vignette and elsewhere), variable trees often get very large, and it's useful to prune them. This kind of pruning would get rid of nodes with small counts. You could, for example, specify that you never want to see nodes with a count less than 5.

**Comment by kishorerathi** [comment]
That will be one most common usage example, a restrictive one though.  A more generalized approach will be to have a condition involving count. This will allow complete flexibility. e.g.

pruneCountCondition   count == 1 | count == 3   => will prune selective nodes
pruneCountCondition   count != 2   => will keep nodes with count of 2
pruneCountCondition   count < 5    => will prune noisy ones

**Comment by nbarrowman** [comment]
Ok, I have added a parameter called `prunesmaller` which implements just the restrictive usage. So for example, `vtree(FakeData,"Sex Severity Group",prunesmaller=4)` prunes any nodes (including missing value nodes) with count less than 4. 

You can install this version of vtree from GitHub using this command:
```
remotes::install_github("nbarrowman/vtree@v2.0.1",force=TRUE)
```
Let me know what you think, and if you spot any problems. I haven't decided, but I might extend it to the other uses you described.
