### ISSUE TITLE
How to use vtree in Shiny?

### ISSUE THREAD

**Issue by trafficonese** [nbarrowman/vtree#5]
The docs say that it is possible to use `vtree` in Shiny, but I couldn't find any example and I didnt manage to figure it out. Could you show how it should be achieved?

Here is what I tried:

```
library(shiny)
library(vtree)
library(DiagrammeR)
library(Hmisc)

getHdata(diabetes)

ui <- fluidPage(
  plotOutput("plot"),
  DiagrammeR::DiagrammeROutput("dia"),
  DiagrammeR::DiagrammeROutput("dia1")
  
)

server <- function(input, output, session) {
  output$plot <- renderPlot({
    vtree(diabetes,"frame",
          pngknit=FALSE,
          horiz=FALSE,height=250,width=850)
  })
  output$dia <- DiagrammeR::renderDiagrammeR({
    vtree(diabetes,"frame",
          pngknit=FALSE,
          horiz=FALSE,height=250,width=850)
  })
  output$dia1 <- DiagrammeR::renderGrViz({
    vtree(diabetes,"frame",
          pngknit=FALSE,
          horiz=FALSE,height=250,width=850)
  })
}

shinyApp(ui, server)
```

**Comment by nbarrowman** [comment]
Thanks for your question. I hadn't tried using vtree with Shiny, but the DiagrammeR package has built-in functions to make it possible.

In response to your question, I modified vtree a bit to make it possible. I'll put a new version of vtree on github in the next day or two.

**Comment by nbarrowman** [comment]
It works with the new release candidate for vtree (v3.0.7). But in your code above, use `grVizOutput` instead of `DiagrammeROutput`.

You can install vtree 3.0.7 using this command:
```
remotes::install_github("nbarrowman/vtree@v3.0.7",build_vignettes=TRUE)
```

_Just in case the above command doesn't build the vignette properly_ (I'm not sure why this is sometimes an issue with `install_github`), try:

```
remotes::install_github("nbarrowman/vtree@v3.0.7",build_opts = c("--no-resave-data", "--no-manual"),build_vignettes=TRUE,force=TRUE)
```
